#!/bin/sh
set -e

help() {
    printf "Usage: ./generate host user hostname port\\n"
    printf "Host: human-readable name you want to give this ssh host\\n"
    printf "User: username you have on this host\\n"
    printf "Hostname: hostname (ip or domain) of the host\\n"
    printf "Port: port SSH is on\\n"
}

if [ -z "$1" ] ; then
    printf "Please provide a host!\\n"
    help
    exit 1
fi

if [ -z "$2" ] ; then
    printf "Please provide a username!\\n"
    help
    exit 1
fi

if [ -z "$3" ] ; then
    printf "Please provide a hostname!\\n"
    help
    exit 1
fi

if [ -z "$4" ] ; then
    printf "Please provide a port!\\n"
    help
    exit 1
fi

HOST=$1
USER=$2
HOSTNAME=$3
PORT=$4

# generate password, add to password manager
pass generate "SSH/${HOST}" 40 > /dev/null

# generate key
ssh-keygen -t ed25519 -f "$HOME/.ssh/${HOST}" -N "$(pass "SSH/${HOST}")" > /dev/null 2>&1

# add ~/.ssh/config entry
cat << EOF >> ~/.ssh/config
Host ${HOST}
    User ${USER}
    HostName ${HOSTNAME}
    Port ${PORT}
    IdentityFile ~/.ssh/${HOST}

EOF

printf "Key has been generated and added to ~/.ssh/config for %s.\\n" "${HOST}"
